### ISSUE TITLE
Why is minSDK 15?

### ISSUE THREAD

**Issue by vekexasia** [trello/RxLifecycle#13]
Hello There,

can you please tell me why is minSDK set to 15?

**Comment by dlew** [comment]
The main reason is eventually (someday) support easier `Activity` binding using [`ActivityLifecycleCallbacks`](http://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html).

We could lower it to 14, but that would be pointless (since the difference in users between 14 and 15 is nonexistant). But if it would make people happier I can do that.

**Comment by vekexasia** [comment]
As far as i can see ActivityLifecycleCallbacks was added in api level 14. 

Is there any bug in api level 14 using ActivityLifecycleCallbacks? I've some apps where the userbase have 3-5% api level 14. for now I use the tools:overrideLibrary but i don't see any reason why we would like to stick with api level 15.

I know RXBinding library had a similar issue and it was raised down to 14. https://github.com/JakeWharton/RxBinding/pull/73

**Comment by dlew** [comment]
Why are you on 14 instead of 15? Do you seriously have *any* users on 14?

**Comment by vekexasia** [comment]
Hello dlew, not me personally.

As mentioned in the ticket i attached a popular library is reporting 4.97% of users having 4.0. 

If you don't want to go down to api level 14 for any reason i'll respect that. No worries :) I was just wondering why you decided to higher the minSdk to 15 since all the code within this library should be compatible at least with 14. (ActivityLifecycleCallbacks included)

Thank you for your time :+1: and for the great lib

**Comment by dlew** [comment]
The chart shown does not differentiate between 4.0 (14) and 4.0.3 (15). If you consider that all their 4.0 is actually 4.0.3 then their chart is roughly in line with what Android currently projects: https://developer.android.com/about/dashboards/index.html

That said, I'm going to bump it down to 14 anyways just so that I don't have to keep fielding this question (since I anticipate seeing it a lot otherwise). It won't make any difference regardless.

**Comment by IlyaEremin** [comment]
Hello. What the reason not to set minSdk to 10 or 9? I mean what features/classes need api 14?

**Comment by dlew** [comment]
Because those are ancient and no one should have to support them.
