### ISSUE TITLE
onCreateView

### ISSUE THREAD

**Issue by sregg** [trello/RxLifecycle#131]
I'm trying to understand why, in RxLifecycle's `RxFragment`, there's no support of the `onCreateView` state, only `onViewCreated`.

Looking at the Fragment's lifecycle, `onCreateView` and `onViewCreated` corresponding closing state is `onDestroyView`, but as `onCreateView` is not handled in `RxFragment`, its corresponding unsubscribe event is `onDestroy` (same as `onCreate`).

Is that a bug or a deliberate decision on your part?

We're seeing a lot of non fatal logs in our Crashlytics indicating that ButterKnife bound views are null in the `onNext` of subscribers subscribed in `onCreateView` and with `compose(bindToLifecycle())`

**Comment by dlew** [comment]
Sorry for the slow reply, been on vacation for the past week.

`onViewCreated()` was originally chosen because the common pattern is that `Fragments` implementing `onCreateView()` won't call `super`, since `Fragment.onCreateView()` normally does nothing and returns null. If `super` is never called then RxLifecycle can't do its work properly.

I searched around the internet for a bit to find examples of how people actually use `Fragments` and all samples I found do not call `super`. [The documentation examples](https://developer.android.com/reference/android/app/Fragment.html) don't call `super`. Even Google's own Android architecture example, which just was released a couple of months ago, don't call `super.onCreateView()` ([example](https://github.com/googlesamples/android-architecture/blob/todo-mvp/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/statistics/StatisticsFragment.java)).

I am sympathetic to the problem - it does seem like something we should fix! However, simply switching to using `onCreateView()` will actually hurt more than help since few people call `super`. Got any other ideas?

**Comment by dlew** [comment]
Also, unfortunately, it seems that `Fragment` is not annotated with `@CallSuper` at all, so there's no expectations setup for which lifecycle methods are expected to have super called on them.

(I know our subclasses define `@CallSuper` but a lint check is not a strong enough guarantee that people will use RxLifecycle correctly.)

**Comment by sregg** [comment]
Ah I see... Makes sense.

I guess we're gonna have to make sure we call stuff in `onViewCreated()`, or if it's in `onCreateView()`, make sure to use `bindUntilFragmentEvent(lifecycle(), FragmentEvent.DESTROY_VIEW)`

Thanks for the help Dan.

**Comment by ultimate-deej** [comment]
@dlew To me a proper solution would be renaming CREATE_VIEW to VIEW_CREATED

**Comment by dlew** [comment]
Renaming it would solve any confusion around people using it directly, but it wouldn't solve the overall problem of the expectation of binding in `onCreateView()` being unbound in `onDestroyView()`.

**Comment by ultimate-deej** [comment]
Well we can restore `CREATE_VIEW` event, which will happen in `onCreateView` this time. Both events will have `DESTROY_VIEW` as their corresponding event.
In case user don't call `super.onCreateView`, that is his fault.

**Comment by xybCoder** [comment]
I have the same problem.
We're seeing a lot of non fatal logs in our Crashlytics indicating that ButterKnife bound views are null in the onNext of subscribers subscribed in onCreateView and with compose(bindToLifecycle())

**Comment by xybCoder** [comment]
@dlew How do you solve the problem?

**Comment by dlew** [comment]
Call `super.onCreateView()`, ignore results.

**Comment by xybCoder** [comment]
thank you
