### ISSUE TITLE
Not unsubscribing may cause unexpected behaviour/leaks/crashes with long-lived Observables 

### ISSUE THREAD

**Issue by masc3d** [trello/RxLifecycle#133]
I stumbled over this when trying to use `rxlifecycle` for binding event subscriptions. Reading the `Unsubscribe` section in the `Readme` explains why it happens, but what is the reason to choose this approach over simply tracking subscriptions?

**Comment by dlew** [comment]
I'm a bit confused by your question, since the point of RxLifecycle is to prevent leaks/crashes with long-lived `Observables`. If you're getting those, that may indicate a problem with RxLifecycle.

The reason we don't just track subscriptions is twofold:

1. There's already `CompositeSubscription` in the RxJava library which does a good enough job of it already, if you need it in some circumstance. (It's legitimate to run RxLifecycle alongside `CompositeSubscription`, depending on needs.)

2. Wrapping is less friendly than just calling `compose()`.

An early version of RxLifecycle *did* just track subscriptions but it was harder to use.

**Comment by masc3d** [comment]
To clarify I'm using `PublishSubject` and `BehaviourSubject` which are exposed by the application model as `Observable`s for event dispatching. I suppose it was rather my fault, as I expected that `.bindToLifecycle` would kind of magically take care of unsubscribing..

How does a `CompositeSubscription` help in this scenario?
I resolved this for now by adding this (rather simplified) extension method, which binds the subscription to the lifecycle:

```kotlin
fun Subscription.bindToLifecycle(fragment: RxFragment): Subscription {
    fragment.lifecycle()
            .filter { it == FragmentEvent.DESTROY_VIEW }
            .subscribe {
                this.unsubscribe()
            }
    return this
}
```
At least for `rxlifecycle-kotlin` this would be just as easy to use, I suppose..

**Comment by dlew** [comment]
I think there's some fundamental misunderstanding here. `bindToLifecycle()` should take care of ending the sequence. While it's not technically the same as unsubscribing, it has the same overall result in terms of cleaning up memory leaks.

Have you taken a look at the sample? It shows how the `Observables` terminate using RxLifecycle.

`CompositeSubscription` helps in situations where you have multiple `Subscriptions` and want to cancel them all at once. If you've only got one `Subscription` then it doesn't matter, I was just guessing you had multiple because that's usually when people start looking into using RxLifecycle.

**Comment by masc3d** [comment]
Is it supposed to work for the scenario I described? I could prepare a test case for it, but maybe it's something you don't even want to explicitly support. Binding the subscription is totally acceptable for me.

**Comment by dlew** [comment]
Yes, it should work when you subscribe to an `Observable`. That's what RxLifecycle is for.

**Comment by masc3d** [comment]
Ok, I found the cause. You're using `BehaviourSubject` and in my code `super.onViewCreated` was called after the bindings, breaking the lifecycle. After correcting this it works as it's supposed to.. sorry for the false alarm and thanks for your feedback.
