### ISSUE TITLE
CancellationException for Observable

### ISSUE THREAD

**Issue by dkhmelenko** [trello/RxLifecycle#187]
Could you explain what is the reason of emitting `onCompleted()` callback for Observables on sequence termination? 

Single and Completable are getting `onError(CancellationException)`, what is nice and helpful. But having `onCompleted()` for Observables doesn't make sense, because actually the sequence can be not completed. Also user can do some action in `onCompleted()` callback being sure that the sequence completed and done with calculation/data processing successfully.

**Comment by dlew** [comment]
I actually prefer `onCompleted`. I couldn't come up with a better solution for `Single` and `Completable` because there's no proper terminal in either case.

The same case of using `onCompleted` for a sequence being complete could be made for `onError` meaning a sequence had an error. It's not an error if it completes early IMO.

Generally speaking, you should be using `onNext` for your processing of data.

**Comment by dkhmelenko** [comment]
Sometimes there is a case when `onNext` is not emitted. In my case it was after applying `filter` operator and no item matched. So `onNext` was not called, but `onCompleted` was emitted. So I cannot rely on `onNext`. 
`onCompleted` means that sequence completed and emitting it in a moment when it could be not completed (destroying activity with active observable) is not a good idea.

At the same point in `onError` we able to specify an exception. And CancelationException fits here very well. Whenever `onError` was emitted user checks the type of the exception in order to process it properly.

**Comment by dlew** [comment]
I still disagree, but it's sort of a moot point because I'm not going to change it to `onError` as it would disrupt too many people's code.

The number of times I've used `onCompleted` is... almost zero. I actually have trouble remembering when I have used it. It was more tempting to use when I first started RxJava but over time you start representing all data as streams and the fact that the stream has completed is usually not important.

**Comment by dkhmelenko** [comment]
I can understand you that it can break many existing code.

On the other side, tests for testing my observable functionality are not working now for me, as `onCompleted` can be emitted at any moment when activity is destroyed and not when sequence is done.

I would suggest to extend functionality in order to give users opportunity to choose which callback should be emitted (`onCompleted` or `onError(CancelationException)`) in case activity is destroyed. This library simplifies the life of many developers and having such feature would make it even better.

I can take care of PR a bit later or can help with ideas.

**Comment by dlew** [comment]
RxLifecycle, at its core, is just a fancy wrapper around `takeUntil`. And the behavior of `takeUntil` with `Observable` is to emit `onCompleted`.

I'm going to stick with that for two reasons: I don't agree that the change is necessary and I believe in keeping libraries as simple as possible.

**Comment by PaulWoitaschek** [comment]
Am I correct that `CancellationException` is still thrown for rx2? Because I can't see that in the readme any longer.

**Comment by dlew** [comment]
It's still in the readme: https://github.com/trello/RxLifecycle/tree/2.x#unsubscription

**Comment by qq2748** [comment]
天哪.....其实还是支持自定义比较好一点
