### ISSUE TITLE
Use `doOnSubscribe` instead of `takeUntil`

### ISSUE THREAD

**Issue by PaulWoitaschek** [trello/RxLifecycle#205]
I find it very invonvenient to use `RxLifecyle` for `Single` and `Completable` because I have to catch the error.

What about using `doOnSubscribe` and just unsubscribing from the `Disposable` when the lifecycle observable emits?

**Comment by dlew** [comment]
Because that won't work. You can't unsubscribe downstream subscribers from upstream. You can only emit notifications downstream, and the only alternative notifications that `Single` and `Completable` allow for are onError.

**Comment by PaulWoitaschek** [comment]
Can you give an example in which cirumstances that doesn't work?

```kotlin
var disposable: Disposable? = null

fun main(args: Array<String>) {
    Observable.interval(1, TimeUnit.SECONDS)
            .doOnSubscribe { disposable = it }
            .subscribe(::println)
    Thread.sleep(3000)
    disposable?.dispose()
    Thread.sleep(3000)
}
```

Prints `0, 1, 2`

**Comment by dlew** [comment]
IIRC, `doOnSubscribe()` does not pass you the same disposable as you'd get if you grabbed the one at the end - it just wraps the disposable for the next operator. In your example those are the same (since `doOnSubscribe()` is called right before `subscribe()`) but if there are more operators below the chain then those wouldn't be unsubscribed.

I just need to sticky this somewhere because someone asks this question about once a month: https://github.com/trello/RxLifecycle/issues/196#issuecomment-271076219

If you don't like how RxLifecycle works, try out [AutoDispose](https://github.com/uber/AutoDispose), which just came out recently and sidesteps this problem.
