### ISSUE TITLE
Another approach for subscription-based lifecycle management

### ISSUE THREAD

**Issue by emakar** [trello/RxLifecycle#233]
Hi! Much thanks for the library, I've been using it for a long time and observed the same issues you mentioned recently here - http://blog.danlew.net/2017/08/02/why-not-rxlifecycle/

However It seems to me there is another solution for RxJava1. Shortly it looks like this:
```java
public void onStart() {
    someSingle.anyOperators()
            .lift(subscriber -> {
                Subscription lifecycleManagingSubscription = lifecycle().takeFirst(appropriateEvent())
                        .subscribe(event -> subscriber.unsubscribe());
                // in case client unsubscribes earlier
                subscriber.add(lifecycleManagingSubscription);
                return subscriber;
            })
            .subscribe(this::handleSuceess, this::handleError);
}
```
- `lifecycleManagingSubscription` init logic is just to show its purpose, not how it should be coded
- Lifted operator is inlined for more clarity, the actual usage would be more like `lift(unsubscribeLifecycleAware())`

I believe there are no threading issues since subscription/lift logic is executed synchronously (so it should behave mostly like direct unsubscription)
The same approach works for `Observable`, `Completable`

I could have missed something obvious though (just a quick insight here). Anyway, I'd be happy to receive any feedback, thanks!

UPD: Well, it only unsubscribes from operator's upstream (technically - from the very first downstream) which can be an annoying restriction. So the only viable usage is to apply it right before subscribe call.
I guess a proper naming like `lift(bindUpstreamToLifecycle())` could help a little

**Comment by dlew** [comment]
The reason we haven't done a solution like this is because of the problem you pointed out - it's only viable if applied directly before the subscribe call. I wasn't comfortable requiring such an unenforceable requirement (especially because much of the time, using it elsewhere in the stream would *seem* to work just fine, so you wouldn't realize they're all wrong).

At this point, though, I'm not going to be changing the behavior of the library. People are using it with its current behavior and it's not worth shaking things up when AutoDispose exists for those who want the other behavior.
