### ISSUE TITLE
androidx support 

### ISSUE THREAD

**Issue by danielesegato** [trello/RxLifecycle#269]
I'm an early androidx adopter and RxLifecycle doesn't work with it, even when enabling the jettifier and androidx support:

```
android.useAndroidX=true
android.enableJetifier=true
```

when I try to `bindToLifecycle` I obtain an error like:

```
Required: LifecycleOwner
Found: Fragment
```
Of course the Fragment is an androidx Fragment and it IS a LifecycleOwner.

But the LifecycleOwner RXLifecycle expect is `android.arch.lifecycle.LifecycleOwner` while the androidx LifecycleOwner is `androidx.lifecycle.LifecycleOwner`.

**Comment by dlew** [comment]
Could you provide a bit more of a stack trace? I haven't actually tried this out myself yet.

**Comment by RubyLichtenstein** [comment]
@danielesegato You can use this quick fix for now
https://github.com/RubyLichtenstein/RxLifecycleAndroidX

**Comment by danielesegato** [comment]
@dlew sorry forgot to answer. It's basically what @RubyLichtenstein said. They simply changed the package of LifecycleOwner and RxLifecycle still look in the other one.

I wrote a simple class like the one Ruby share to keep going for my project.

**Comment by jcsla** [comment]
@dlew 
Please merge this PR to another branch. Thanks.

**Comment by dlew** [comment]
It's still not exactly clear to me why the Jetifier doesn't work here, since the point of it is to change `android.arch.*` to `androidx.*`. If it's not doing that, then we should be filing bugs with the Jetifier, not trying to change this lib. Changing this lib would cause problems for anyone who *isn't* updated to AndroidX yet.

At the very least, what we'd need to do is support is to create another artifact, not modify the existing ones (since that'd break back-compat).

**Comment by dlew** [comment]
Here's what I've decided to do for now: I'm updating all the dependencies (since referencing android arch 1.0.0 instead of 1.1.0 was causing problems for R8). If, after that update, AND after Jetifier is stable, people are still having Jetifier issues, then we can look into a longer-term solution.

However, what I explicitly do not want to do is just update the package names in the library. That will break everyone who isn't switching to AndroidX just yet, which is completely fair given that it's only in beta.

**Comment by ahulyk** [comment]
Jetifier works fine. 
You just need to add following extensions for kotlin:
[RxLifecycleKtx for androidX](https://github.com/RubyLichtenstein/RxLifecycleAndroidX/blob/master/RxLifecycleKtx.kt)

**Comment by tvhieuit** [comment]
I'm just invalidate caches / restart. So it worked :D
