### ISSUE TITLE
First time onStart cost a long time

### ISSUE THREAD

**Issue by Ruowenmei** [trello/RxLifecycle#297]
The first time execut onStart() will cost a long time in the app's First Activity which extends RxFragmentActivity

**Comment by Ruowenmei** [comment]
The Version is rxlifecycle-components:2.1.0

**Comment by dlew** [comment]
I have my doubts that the issue lies within RxLifecycle itself since all it does is call `BehaviorSubject.onNext()` once within `onStart()`. Chances are you are either using that lifecycle call to invoke a bunch of behavior synchronously, or there's some non-RxLifecycle code that is slowing down startup.

Could you provide a sample showing the performance issue?
