### ISSUE TITLE
I can't load RxlifecycleAndroidKotlin2

### ISSUE THREAD

**Issue by qianshengta** [trello/RxLifecycle#307]
I can't load  'com.trello.rxlifecycle2:rxlifecycle-android-lifecycle-kotlin:2.2.2'
**This is an error message：**

```
Duplicate class android.arch.core.util.Function found in modules classes.jar (android.arch.core:runtime:1.1.0) and common-1.1.1.jar (android.arch.core:common:1.1.1)

Go to the documentation to learn how to Fix dependency resolution errors.
```

Does this mean that it is duplicated with other open source libraries?

**Comment by dlew** [comment]
You should follow the advice it says - "Go to the documentation to learn how to Fix dependency resolution errors."

Again - I can't emphasize this enough - this forum is for *bug reports* for *this specific library*. What you've posted here (and repeatedly in the past few days) are support requests. I do not offer one-on-one support because I don't have time for it, sorry.

**Comment by qianshengta** [comment]
I'm very sorry, because it's me who takes over other people's projects. And it was my first exposure to RxLifecycle, so I couldn't tell if the problem with Kotlin refactoring was RxLifecycleor the rest of the project.
Again, I'm sorry for my previous irrational interruption.
