### ISSUE TITLE
NoSuchMethodException on androidx.fragment.app.Fragment.onCreate

### ISSUE THREAD

**Issue by rickytribbia** [trello/RxLifecycle#336]
Thank you for your great library! 

We've some occurrencies of this crash:
```
Caused by java.lang.NoSuchMethodException
xxxx.xxxxxxx.xxxxxx.views.fragments.notifications.NotificationsFragment.<init> []
```

with this stacktrace: 

```
java.lang.Class.getConstructor0 (Class.java:2332)
androidx.fragment.app.Fragment.onCreate (Fragment.java:1867)
com.trello.rxlifecycle4.components.support.RxFragment.onCreate (RxFragment.java:78)
androidx.fragment.app.Fragment.performCreate (Fragment.java:2949)
androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:276)
com.trello.rxlifecycle4.components.support.RxFragmentActivity.onCreate (RxFragmentActivity.java:73)
```

We can't understand how could be possibile that it could not find app.Fragment constructor when initialize our Fragment that subclass RxFragment. 

Any advice? 

we're using: 
```
version_lib_rxlifecycle = "4.0.2"

api "com.trello.rxlifecycle4:rxlifecycle-kotlin:$version_lib_rxlifecycle"
api "com.trello.rxlifecycle4:rxlifecycle-components:$version_lib_rxlifecycle"
```

**Comment by dlew** [comment]
This does not appear to be an RxLifecycle issue. Instaed, I believe the issue here is that you need a zero-arg constructor for every `Fragment`. Otherwise the framework can't restore a `Fragment` that's been destroyed (e.g. due to a config change like rotating the device).

See more here: https://stackoverflow.com/a/56669540
