### ISSUE TITLE
onComplete being called onDestroy

### ISSUE THREAD

**Issue by BugsBunnyBR** [trello/RxLifecycle#42]
Hi, I got some weird behavior with retrofit Observables when used together with RxLifecycle.
I am not quite sure, but by this documentation[1] the default behavior of Observables is to don't call onComplete if onError is fired, but the onComplete method is being called in onDestroy of Actvity/Fragment.
Is this the right thing to do? 
In the code below I can get the  openHomeScreen() to be called. Should I move it to onNext()?
```java
mUserApiClient
                .get()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .compose(RxLifecycle.bindFragment(lifecycle()))
                .subscribe(
                        new Subscriber<User>() {
                            @Override
                            public void onCompleted() {
                                openHomeScreen();
                            }

                            @Override
                            public void onError(Throwable e) {
                                handleRequestError(e);
                            }

                            @Override
                            public void onNext(User user) {
                                mUserManager.setUser(user);
                            }
                        });
    }
```
[1] http://reactivex.io/documentation/observable.html

**Comment by dlew** [comment]
The expected behavior of RxLifecycle is to call `onCompleted` when it terminates a subscription.

I suggest moving `openHomeScreen()` to `onNext()`, especially since it looks like you're only planning on getting one item emitted.

**Comment by BugsBunnyBR** [comment]
Ok,
I will move to onNext(), but I think there may be some case where onNext() is called multiple times.
Is this the standard rx behavior? When I handle the Subscription.unsubscribe() by myself it does not seems to call Subscriber.onComplete()... Document this maybe?
Thanks.

**Comment by dlew** [comment]
If you call `unsubscribe()` then it will not call `onCompleted()`.

Previous versions of RxLifecycle attempted to unsubscribe rather than complete (for this exact reason), but that led to a whole class of bugs that were unfixable. The current solution is a trade-off: In most cases it's fine, and when you do actually need the behavior of `unsubscribe()` then you can still do it yourself manually.

**Comment by tbsandee** [comment]
I was confused by this too -- and still am a bit. The README says it will "unsubscribe in the opposing lifecycle event". Is that just a bit out of date or is there some other nuance I'm missing in this conversation?

**Comment by dlew** [comment]
Yeah, the docs are out of date. I'll fix them up soon.

**Comment by dlew** [comment]
What do people think of the new explanation in #43?

**Comment by tbsandee** [comment]
I like it, definitely helps understand what to expect. Thank you.

I'm new to Rx so a lot of this may be clear to someone who is fully engaged, but I do have a related question since I have your ear. When used in this way, will completing the sequence typically clear references to the Android object (fragment, activity, etc) barring any other strong references leaking out? You often hear about needing to unsubscribe() but it's not immediately clear that a completed sequence has the same effect.

**Comment by dlew** [comment]
I wrote a sample app that should help clear up your confusion: https://github.com/dlew/android-subscription-leaks

**Comment by ypresto** [comment]
How about use lift() to get subscription instance and unsubscribe instead of onComplete()?

I have small helper to use with CompositeSubscription.
https://gist.github.com/ypresto/accec4409654a1830f54

**Comment by ypresto** [comment]
Ah, ok I found  #19 and understood why onCompleted() is required.
