### ISSUE TITLE
Should there be an ActivityEvent.ON_SAVE_INSTANCE_STATE?

### ISSUE THREAD

**Issue by dalewking** [trello/RxLifecycle#52]
We are running into an issue where there are some things that cannot occur after onSaveInstanceState is called (e.g. fragment transactions) and we want to make sure that the Rx chain is unsubscribed at that point, but the activity lifecycle methods do not cover that. Pause is close but there is no guaranteed order between onPause and onSaveInstanceState which still leaves a possibility of an error.

**Comment by dlew** [comment]
I'm working on another lib right now that should invalidate this need (if it works out). It has a lot more listeners in general which would let you hook into save instance state. 

I'm going to wait on that until I see if the other lib is viable, especially since if it *does* work out this library would simply build on top of it (or maybe even be completely invalidated).

**Comment by dlew** [comment]
See: https://github.com/trello/navi/
