### ISSUE TITLE
Espresso IdlingResource

### ISSUE THREAD

**Issue by tommyd3mdi** [trello/RxLifecycle#65]
I have a rather hard time to get `RxJava` in conjunction with `RxLifecycle` to play nicely during tests. I created a custom `IdlingResource` basically mimicking [this prior art](https://github.com/rosshambrick/RxEspresso/blob/master/src%2Fmain%2Fjava%2Fcom%2Frosshambrick%2Frxespresso%2FRxIdlingResource.java), but I see many, many subscriptions that are started, but never stopped, thus the idling resource never getting idle.

I realized that it may have something to do with `RxLifecycle` since it emits lifecycle events on a never-ending stream and indeed, when I remove my `compose(bindToLifecycle())` calls, it kind of works. Now the interesting question is: Do you know of any way to detect (and ignore) subscriptions from `RxLifecycle` or is deactivating the `bindToLifecycle()` call in test mode altogether the only option?

**Comment by tommyd3mdi** [comment]
Ah, just figured, `bindToLifecycle()` is final in `Rx{Fragment,Activity,...}`, so it cannot be easily overridden...

**Comment by dlew** [comment]
The reason it's `final` is that `ActivityLifecycleProvider` is an interface, so it should be mockable if you need to override its behavior for tests. Outside of tests there's pretty much no reason to override it (that I know of).

I don't agree with how `RxIdlingResource` works: a subscription isn't an indicator of background activity! There are plenty of cases, for example if you're using a subscription detect changes in an `EditText`, or a subscription for when a button is clicked... I think you need to be a lot more specific about *which* subscriptions should cause idling, rather than just tracking all of them.

**Comment by tommyd3mdi** [comment]
Ok, understood. You're right, a subscription can run without any special threading set up. I guess I have to find another way of abstracting this. My start with Rx was already steep and now that threading issues come into the mix (figuring out on which thread (sub-)observables and their subscriptions are executed is a little messy), things get very messy.

Sorry for the noise, I figure out something else.
