### ISSUE TITLE
Support for ListFragments

### ISSUE THREAD

**Issue by erikpedersen** [trello/RxLifecycle#71]
We use some ListFragments in our apps and it would be nice to have an Rx component that we can extend in these cases. It appears to be a quick addition so I can make a PR with this support if that makes sense. Thanks!

**Comment by dlew** [comment]
I'm kind of two minds on this one. It would be easy to add `ListFragment` support... but where does this end? There are (by a quick count) over 20 fragments in the Android library. Plus, the library was purposefully setup with interfaces so that you can supply your own implementations (since there are so many potential base classes out there).

On the other hand, I know how this will save a bit of work.

Can you make an argument for why `ListFragment` should be one of the officially endorsed base classes? To me, it seems to fall below the threshold of necessity since you can fairly easily reproduce much of its capabilities without using it.

**Comment by erikpedersen** [comment]
I totally understand and appreciate your position on this. From a purely "selfish" point of, this is the only other type of fragment outside the core ones already support here that I have ever bothered to use in our apps. The rest of them (except for maybe the PreferenceFragment) seem so specific in use case, that I haven't really considered them. Of course, I'm sure other developers have explored them and perhaps have utilized them. If I had to come up with a (tenuous, at best) argument here, I guess it just feels to me that ListFragment is on the edge of being one of the more generic types of fragments out there that developers may have used in common app use cases. I'm totally on board with you if you feel like ListFragment shouldn't be part of the core, but thanks for at least considering it!

**Comment by dlew** [comment]
I've slept on it and I think I'm going to say "no" on this one for a couple reasons (in addition to the ones above):

- I've felt for a while that both `ListActivity` and `ListFragment` are too specific - they work in some very broad circumstances but are otherwise inflexible.
- If this was considered a core `Fragment`, then there would be a `RecyclerFragment`, but there isn't one.

It shouldn't be too hard to write your own `RxListFragment`, though - just copy the `RxFragment` code and extend from a different class. :)
