### ISSUE TITLE
Make bindUntilEvent() and bind() public?

### ISSUE THREAD

**Issue by hzsweers** [trello/RxLifecycle#76]
These methods are actually generic enough that they can be reused for other lifecycles (such as controllers in MVP patterns). Would be nice to use them rather than copying in logic and mixing in activity and controller lifecycles.

**Comment by hzsweers** [comment]
Same with `OutsideLifecycleException`

**Comment by dlew** [comment]
I'm always hesitant to open things up, since I've always considered that more of an implementation detail, especially `bind()`.

Would using `takeUntil` + [Navi](https://github.com/trello/navi) help out? Navi is better designed for generic inputs.

**Comment by hzsweers** [comment]
I'm not sure Navi helps here since it looks like it would still require writing our own bind() implementations

**Comment by dlew** [comment]
I have separate thoughts on `bindUntilEvent()` and `bind()`.

Looking on it now, it seems like we shouldn't even have `bindUntilFragmentEvent()` and `bindUntilActiviyEvent()`. `bindUntilEvent()` can use generics to figure out the difference. I think we can open that up and deprecate the first two (or even just remove them entirely).

Regarding `bind()` though (and really, your entire original problem). Suppose we open up `bind()`. Then we also have to open up `ACTIVITY_LIFECYCLE` and `FRAGMENT_LIFECYCLE`, since those are the inputs. And your implementation would have to know which one to pass in. I'm not sure how that saves you any effort, generically speaking, since you still have to know whether you're working with Activities or Fragments. The same applies to `bindUntilEvent()` since you'd have to know which you're targeting.

**Comment by hzsweers** [comment]
You wouldn't necessarily have to open them up, though having public examples might be helpful for what I'm about to suggest. The idea is so that you could pass other lifecycles like `CONTROLLER_LIFECYCLE` or a custom `ACTIVITY_LIFECYCLE` (e.g. your base actvitiy has other callbacks you want to expose). What's great about the `bind()` implementation is that it doesn't care if the lifecycle is of an activity, fragment, or goat. The only implementation change would maybe be to use `.equals()` rather than `==` to allow for non-enum parameters, but that would be a separate discussion I think.

Perhaps using an interface that behaves the same way as `Func1` could make it more clear? Something like `LifecycleMapping#map(event)` maybe? Then just create a `Func1` internally in `bind()` that just calls it under the hood.

**Comment by dlew** [comment]
I see your point. I'll think about it.

It almost seems like this could lead to a split in the library, where `RxLifecycle` is all about binding generic subscriptions to any given lifecycle and `RxAndroidLifecycle` could be about binding specifically to Android lifecycles.

**Comment by hzsweers** [comment]
Yeah that could work
